// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNEGm3NZZWXnMhx_KzaUq-a2zFEQ-wPwU',
    appId: '1:1000452448312:web:604a93024e902a0b1386cd',
    messagingSenderId: '1000452448312',
    projectId: 'learning-app-7be64',
    authDomain: 'learning-app-7be64.firebaseapp.com',
    storageBucket: 'learning-app-7be64.firebasestorage.app',
    measurementId: 'G-LSJ1QYMLKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9hZoy1QSE4U6vLcy3cs0ZO5YWEyvFAdg',
    appId: '1:1000452448312:android:5ab7ff121ebd57161386cd',
    messagingSenderId: '1000452448312',
    projectId: 'learning-app-7be64',
    storageBucket: 'learning-app-7be64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7exZ_pBnLbW2fK8G9l8G6EAbLaX1WKZg',
    appId: '1:1000452448312:ios:146ae4d8e5b11cde1386cd',
    messagingSenderId: '1000452448312',
    projectId: 'learning-app-7be64',
    storageBucket: 'learning-app-7be64.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7exZ_pBnLbW2fK8G9l8G6EAbLaX1WKZg',
    appId: '1:1000452448312:ios:146ae4d8e5b11cde1386cd',
    messagingSenderId: '1000452448312',
    projectId: 'learning-app-7be64',
    storageBucket: 'learning-app-7be64.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNEGm3NZZWXnMhx_KzaUq-a2zFEQ-wPwU',
    appId: '1:1000452448312:web:b8233dfa7e4a3e2e1386cd',
    messagingSenderId: '1000452448312',
    projectId: 'learning-app-7be64',
    authDomain: 'learning-app-7be64.firebaseapp.com',
    storageBucket: 'learning-app-7be64.firebasestorage.app',
    measurementId: 'G-KWKNLFW6HD',
  );
}
